// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type AdditionRequest struct {
	Number1 *int `json:"number1"`
	Number2 *int `json:"number2"`
}

type AdditionResponse struct {
	Number3 *int `json:"number3"`
}

type CalculationRequest struct {
	Operator *string `json:"operator"`
	Number1  *int    `json:"number1"`
	Number2  *int    `json:"number2"`
}

type CalculationResponse struct {
	Number3 *int `json:"number3"`
}

type DivisionRequest struct {
	Number1 *int `json:"number1"`
	Number2 *int `json:"number2"`
}

type DivisionResponse struct {
	Number3 *int `json:"number3"`
}

type MultiplicationRequest struct {
	Number1 *int `json:"number1"`
	Number2 *int `json:"number2"`
}

type MultiplicationResponse struct {
	Number3 *int `json:"number3"`
}

type SubtractionRequest struct {
	Number1 *int `json:"number1"`
	Number2 *int `json:"number2"`
}

type SubtractionResponse struct {
	Number3 *int `json:"number3"`
}
